### ISSUE TITLE
WordPress 4.9.4 support

### ISSUE THREAD

**Issue by dxgldotorg** [daveross/http2-server-push#20]
The current version of the HTTP/2 Server Push plugin is currently marked as tested for only up to WordPress 4.6.10.  Do you have any plans to update it to 4.9.4?

**Comment by dana-ross** [comment]
Believe it or not, I've been thinking about this plugin a lot lately. I'm sure that's a surprise given how long its been since I updated it 😜

This comment is going to be a little long. It's a little bit rant, a little bit blog post. Lots of thoughts I need to get out and you've given me a good opportunity here. Don't worry, it's not directed at you personally, but more the state of web software in general.

_TL;DR version: HTTP/2 Server Push hasn't lived up to the hype and may even make performance worse in some circumstances. The proposed solution has performance & privacy implications._ 

HTTP/2 Server Push sounds amazing at a conceptual level. Instead of the browser waiting to parse the HTML document and request assets it needed, the server proactively sends them. It was going to save us so much time! But as more sites have adopted it, it's become clear things aren't so simple in the real world and there are fundamental problems with the protocol itself. As one member of the IETF put it ["Wow, HTTP/2 Server Push is now shorthand for "something we over-engineered.""](https://twitter.com/mnot/status/976771564137009152).

The Google Chrome team did some research into Server Push performance, and documented [a set of Server Push best practices](https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/). One thing they found is Sever Push only makes sense as a way to fill idle time in the TCP/IP connection, meaning a server should be tracking the congestion window of every HTTP/2 stream to decide if it even makes sense to push resources or not. If there's no room for a file in the pipe, then performance for that file is about on par with waiting for the browser to request it. Shockingly, "pushing more than cwnd bytes has no additional benefit and _can actually hurt performance_" (emphasis mine).

When I started looking at Server Push, there wasn't much concern about pushing resources that the client already received. The protocol specifies a way for the server to say "I'm going to push this file to you" and for the client to respond "Nah, I'm good. I already have that one" (`RST_STREAM`). But the overhead of this conversation turns out to be a lot of wasted bytes. One solution has been to use a "cache digest" in a cookie to track what files have already been sent. That solves the issue of keeping the server from sending files the browser doesn't need, but it's also raises privacy concerns: if my digest says I have a cached copy of a script only found on the Chimichanga section of Food Fans Forum, you can guess which Mexican-American food won my allegiance. It also means the browser has to send the cookie or header with every request (more bytes!) and the server needs to tailor the files it pushes to each client.

There's an [IETF draft to add cache digests to HTTP/2 itself](https://tools.ietf.org/html/draft-ietf-httpbis-cache-digest-03) but it hasn't gotten very far yet. The H2O web server, always on the cutting edge of HTTP/2 Server Push, implemented their own cache digest solution and have been refining it to make it more like the IETF solution. But nginx, one of the biggest web server programs in use today, just tells people ["don’t push resources that a client is likely to already have cached."](https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/).

Until the IETF, browser makers, and web server software creators work all this out on their own, they've expected we'll take care of this in the app software. But, it's no secret that WordPress _by itself_ doesn't scale well by default. [WordPress needs full-page caching](https://10up.github.io/Engineering-Best-Practices/php/#page-caching) to support more than a personal blog's usual amount of traffic. And tailoring the Server Push resources to a particular person's browser session with every request isn't compatible with trying to serve an identical, static page to everyone.

This plugin tries to Server Push every script and CSS file WordPress knows it's going to output, which doesn't fit with Google's recommendation of using Server Push to fill times of low congestion over a TCP/IP connection. It could even be counterproductive. Ideally, it should be trying to push one or two files that make the most sense to be pushed, and the only way to know that is to try different scenarios and track performance numbers. That's something a developer needs to do, and if they're doing that then they can set the `Link:` headers themselves.

And, lastly, WordPress's fundamental architecture is a relic of a simpler time. Because it lets plugins and themes output whatever arbitrary markup they want to into pages, I'm still coming across code that prints `<script>` and `<link rel="stylesheet">` tags directly into page content and those files will never be pushed. And there are lesser-used caching plugins out there which only save HTML content, not the headers, so Server Push only happens on a cache miss when they're used. I kind of miss Drupal's built-in cache support, which kept their community from coming up with 50 different caching plugins on their own.

Anyway, I don't want people thinking they can just install this plugin and their sites will magically get faster because that's not the case. It's become apparent we can't approach Server Push naively like this if we want to make the best use of it.

I've been thinking of officially abandoning this plugin but I'm waiting to see if cache digests get anywhere by, say, June 2018. It's not just a matter of having time to maintain plugins (I don't), I actually feel it's irresponsible for me to let this plugin continue to exist if I know it could actually hurt performance on people's sites. And I'm not sure if I can continue supporting the protocol if the privacy issues with cache digests aren't addressed.

**Comment by dxgldotorg** [comment]
I only asked because Server Push support landed in nginx 1.13.9 recently, and I noticed your add-on hasn't been updated or tested with the latest WordPress.

**Comment by dana-ross** [comment]
I'll probably test it out with WP 4.9.4 and push out an update. There was a Pull Request last week that fixed a WPML issue and I'd like to get that out the door as well.

**Comment by dana-ross** [comment]
Just tested on 4.9.4 and pushed out v1.4
