### ISSUE TITLE
520 errors

### ISSUE THREAD

**Issue by dana-ross** [daveross/http2-server-push#7]
some users are reporting HTTP 520 errors. See https://wordpress.org/support/topic/getting-a-520-error-on-wp-admin-after-plugin-install?replies=3

520 is a catchall error code for issues the server doesn't otherwise know how to handle. That's going to make this difficult to troubleshoot. Possibly HHVM related?

**Comment by dana-ross** [comment]
Possibly helpful? https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520

**Comment by yasserkaddour** [comment]
Hi Dave, I just installed your plugin to take advantage of the recent support of [server push by cloudflare](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) and I had the same issue, I am using a bluehost hosting and no HHVM. Maybe it's cloudflare related since server push support is recent.

Let me know if there is anything I can do to help you.
Thanks.

**Comment by dana-ross** [comment]
In Cloudflare's 520 doc linked above, they mention an issue if HTTP headers are bigger than 8k. Here are Cloudflare's docs on testing against the "origin" server to rule out the header issue https://support.cloudflare.com/hc/en-us/articles/219304477

**Comment by lorenzoaiello** [comment]
Same issue here, however this is occurring more with asset-heavy plugins (eg. Visual Composer).

Is it perhaps an idea to have an option to run http2 server push only on the front-end and have it disabled in wp-admin?
